### ISSUE TITLE
Log.error/warn/trace/...(Throwable) doesn't log Throwable Message

### ISSUE THREAD

**Issue by gdaniel** [atlanmod/Commons#1]
If you try to log an exception using `Log.error(e)` the displayed log is like:
```
[ERROR] 21:39:57,012 - null
java.net.SocketTimeoutException: test
	at a.b.c 
        [...]
```

I think it should be better to have a log like the following one:
```
[ERROR] 21:39:57,012 - java.net.SocketTimeoutException: test
	at a.b.c 
        [...]
```

**Comment by yvernageau** [comment]
Exception formatting is related to the logging' implementation, not the base API. The base API only notifies the implementation of an event, without any processing (except for formatted messages).

In your case, I assume you're using Log4j, so this formatting can be configured by adapting the pattern in the `log4j2.xml` file.
See https://logging.apache.org/log4j/2.x/manual/layouts.html#Patterns for more information, under the "exception" section.
